### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by C00reNUT** [raven38/rf_inversion#1]
Thank you for making this implementation in code, I never liked the COMFY snakes :)

Could I ask you for something - could you add 1 or 2 more command line examples, for example how to transfer style from image to image etc.? Thank you!

**Comment by raven38** [comment]
`python main.py --image examples/man.jpg --prompt "Face of a boy in disney 3d cartoon style" --output outputs/man_cartoon_gamma03_eta08_s0e3_st95.jpg --eta 0.8 --start_timestep 0 --stop_timestep 3 --gamma 0.3`
<img src="https://github.com/user-attachments/assets/1532a07a-f6db-4b8c-9feb-abe2e05e5257" width="20%"/>

**Comment by raven38** [comment]
@C00reNUT Thank you for your interest!
I updated the inversion code and README.md. Let's check additional examples in README.md.
