### ISSUE TITLE
Results not satisfied

### ISSUE THREAD

**Issue by yuxu915** [raven38/rf_inversion#3]
Hi, thanks for your contribution, I run code with default configuration, the result is as follow(add glasses to face)
![image](https://github.com/user-attachments/assets/6fca7f2c-3052-4d9c-8cb6-77f685b066c6)
I would like to know where the problem might be, could you please help?
Thank you.

**Comment by raven38** [comment]
For adding glasses, we need custom config as stated in the paper. 
For example, '--eta 0.7 --start_timestep 16 --stop_timestep 25'
I think you can try other timestep parameters.

**Comment by wuyou22s** [comment]
> For adding glasses, we need custom config as stated in the paper. For example, '--eta 0.7 --start_timestep 16 --stop_timestep 25' I think you can try other timestep parameters.

still not work...

**Comment by bookkkker** [comment]
have the same questions too... May you had any methods yet?

**Comment by yuxu915** [comment]
> have the same questions too... May you had any methods yet?

no idea..seems very parameter sensitive.

**Comment by raven38** [comment]
I added the `num_images` argument and test some configurations.
` python main.py --image examples/man.jpg --prompt "A portrait of a man wearing glasses" --num_images 4 --output outputs/man_glasses_gamma02_eta07_s6e18_st05.jpg --eta 0.7 --gamma 0.2 --start_timestep 6 --stop_timestep 15  --strength 0.8`

<img src="https://github.com/user-attachments/assets/1868cf81-b562-4fa9-bb17-15984dd4b0c5" width="20%" />
<img src="https://github.com/user-attachments/assets/5b121234-7d14-4e0d-9e07-d2a54bb52f3b" width="20%" />
<img src="https://github.com/user-attachments/assets/bba1b93a-851d-47c8-a360-a9f8f7bbcc95" width="20%" />
<img src="https://github.com/user-attachments/assets/439608e1-9ba9-4ac7-b0ed-6a2e4f379cf5" width="20%" />


`python main.py --image examples/man.jpg --prompt "A portrait of a man wearing glasses" --num_images 4 --output outputs/man_glasses_gamma02_eta07_s6e15_st09.jpg --eta 0.7 --gamma 0.2 --start_timestep 6 --stop_timestep 15  --strength 0.9`

<img src="https://github.com/user-attachments/assets/13fdb149-3ae9-49ee-ba56-468fe441ae1b" width="20%" />
<img src="https://github.com/user-attachments/assets/c2a6494f-6804-47d5-b35f-53fc25db1841" width="20%" />
<img src="https://github.com/user-attachments/assets/cc777fd7-33c4-4509-9ac2-50c0092b0b27" width="20%" />
<img src="https://github.com/user-attachments/assets/f64a3e80-6802-4330-8330-2ce3f09e9b7e" width="20%" />

**Comment by raven38** [comment]
The results are unstable.

**Comment by yuxu915** [comment]
> I added the `num_images` argument and test some configurations. ` python main.py --image examples/man.jpg --prompt "A portrait of a man wearing glasses" --num_images 4 --output outputs/man_glasses_gamma02_eta07_s6e18_st05.jpg --eta 0.7 --gamma 0.2 --start_timestep 6 --stop_timestep 15 --strength 0.8`
> 
> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044268-1868cf81-b562-4fa9-bb17-15984dd4b0c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDI2OC0xODY4Y2Y4MS1iNTYyLTRmYTktYmIxNy0xNTk4NGRkNGIwYzUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY4MWFlOThhYmIyODNkYzVmZWM3NGE4MGNjOWZjM2M2NmRmNDBlMDJlYWU0YzJjYTAzNjA1OTdmZjJiN2NjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GU7wBTr_9cvaQ8YdyHJsfpOm0236En__jlkvLWJeVlI"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044590-5b121234-7d14-4e0d-9e07-d2a54bb52f3b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDU5MC01YjEyMTIzNC03ZDE0LTRlMGQtOWUwNy1kMmE1NGJiNTJmM2IuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc5MjE5MjdlODMzYWYwOTE2OTBmY2I0NGVhZDAyNDk0NmM1ZjA0NDc4Y2Y4YjQ2ZWQyNjcwNTc2Yzg1MzU4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.him1SY-sKnCsBnb1wa-w59TECVe1lH1fwzMPyPdH0aQ"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044607-bba1b93a-851d-47c8-a360-a9f8f7bbcc95.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDYwNy1iYmExYjkzYS04NTFkLTQ3YzgtYTM2MC1hOWY4ZjdiYmNjOTUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcwZDRjNmQ2OTgxY2MwNjk2NzZlZWYyNjdmMWI1OGU0YmFkMzFhNzQxYjZlOTc1YTdkZmIxODdlMmMxZmY0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f_ZCovmcL8WnH1Ls0IekxwMWBwSboEWcw76x6pLMcgY"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044616-439608e1-9ba9-4ac7-b0ed-6a2e4f379cf5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDYxNi00Mzk2MDhlMS05YmE5LTRhYzctYjBlZC02YTJlNGYzNzljZjUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdjMGU1OThmNzQyZTQ0NTBjYTdkMjlhMWY2Yjk0ZWE5OGM5YTgwOWIxYjY2OWZkZmJiYzc0Yjc4ZDRkMTMyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JPTzd2BAyx8llcwBaJx238EyChgoFRZoVMur6zlEkM8">
> `python main.py --image examples/man.jpg --prompt "A portrait of a man wearing glasses" --num_images 4 --output outputs/man_glasses_gamma02_eta07_s6e15_st09.jpg --eta 0.7 --gamma 0.2 --start_timestep 6 --stop_timestep 15 --strength 0.9`
> 
> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044639-13fdb149-3ae9-49ee-ba56-468fe441ae1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDYzOS0xM2ZkYjE0OS0zYWU5LTQ5ZWUtYmE1Ni00NjhmZTQ0MWFlMWIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM2NDZiZTI5YTQ4MjFhNGVmYjFmNTI3YzY2ZTYzNjExMmUyNGY0NjM5OTMwOGQzY2FhM2E2NGI3ZmQ0MjEwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Fk7co5VIbuuKPUnDy2y79CdwujouZ1JFA8aFI2vMm1M"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044653-c2a6494f-6804-47d5-b35f-53fc25db1841.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDY1My1jMmE2NDk0Zi02ODA0LTQ3ZDUtYjM1Zi01M2ZjMjVkYjE4NDEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA3Y2Y5NThmNzA5OWI3MThlYWRhZWYxMjFmNDBhODlmMTM2ZmVkNGJkYjM4ZTVhODMxMzgyMDg0ODZhNTkxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oLetqtEuROYFjsJ5t2dZzXpfDXAiwULdcmClvGQ4FAc"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044659-cc777fd7-33c4-4509-9ac2-50c0092b0b27.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDY1OS1jYzc3N2ZkNy0zM2M0LTQ1MDktOWFjMi01MGMwMDkyYjBiMjcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE0MzEzNTVkODM5MDY4MTE3MjI1Mjk4YzgwMDNlZWJhMTRiOGEyMTU3NzNjZDE3YTI5NmQ5YzEwMTgyODFkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pTHkpqwhfTubI5R9ighGk5rm4D3tdIXWEq3WAxC6how"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044677-f64a3e80-6802-4330-8330-2ce3f09e9b7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDY3Ny1mNjRhM2U4MC02ODAyLTQzMzAtODMzMC0yY2UzZjA5ZTliN2UuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRmNWRiZDliOTFmNDk3YjlkYWM5YTFlNmUzZTY4NTk2ZDc4MTU0NjdjYTY4NGQxOTI4NTFkZjc2OGQ5N2UyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u9xt0qMtfaZLJtP21qtVssjLq2VU_2_N2xUeL7KmZfE">

Thank you for sharing. It seems different seeds have a significant impact on the results. By the way, do you have any experience with parameter tuning for other types of editing that you could share(e.g. styles)?

**Comment by yuxu915** [comment]
> I added the `num_images` argument and test some configurations. ` python main.py --image examples/man.jpg --prompt "A portrait of a man wearing glasses" --num_images 4 --output outputs/man_glasses_gamma02_eta07_s6e18_st05.jpg --eta 0.7 --gamma 0.2 --start_timestep 6 --stop_timestep 15 --strength 0.8`
> 
> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044268-1868cf81-b562-4fa9-bb17-15984dd4b0c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDI2OC0xODY4Y2Y4MS1iNTYyLTRmYTktYmIxNy0xNTk4NGRkNGIwYzUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY4MWFlOThhYmIyODNkYzVmZWM3NGE4MGNjOWZjM2M2NmRmNDBlMDJlYWU0YzJjYTAzNjA1OTdmZjJiN2NjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GU7wBTr_9cvaQ8YdyHJsfpOm0236En__jlkvLWJeVlI"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044590-5b121234-7d14-4e0d-9e07-d2a54bb52f3b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDU5MC01YjEyMTIzNC03ZDE0LTRlMGQtOWUwNy1kMmE1NGJiNTJmM2IuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc5MjE5MjdlODMzYWYwOTE2OTBmY2I0NGVhZDAyNDk0NmM1ZjA0NDc4Y2Y4YjQ2ZWQyNjcwNTc2Yzg1MzU4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.him1SY-sKnCsBnb1wa-w59TECVe1lH1fwzMPyPdH0aQ"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044607-bba1b93a-851d-47c8-a360-a9f8f7bbcc95.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDYwNy1iYmExYjkzYS04NTFkLTQ3YzgtYTM2MC1hOWY4ZjdiYmNjOTUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcwZDRjNmQ2OTgxY2MwNjk2NzZlZWYyNjdmMWI1OGU0YmFkMzFhNzQxYjZlOTc1YTdkZmIxODdlMmMxZmY0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f_ZCovmcL8WnH1Ls0IekxwMWBwSboEWcw76x6pLMcgY"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044616-439608e1-9ba9-4ac7-b0ed-6a2e4f379cf5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDYxNi00Mzk2MDhlMS05YmE5LTRhYzctYjBlZC02YTJlNGYzNzljZjUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdjMGU1OThmNzQyZTQ0NTBjYTdkMjlhMWY2Yjk0ZWE5OGM5YTgwOWIxYjY2OWZkZmJiYzc0Yjc4ZDRkMTMyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JPTzd2BAyx8llcwBaJx238EyChgoFRZoVMur6zlEkM8">
> `python main.py --image examples/man.jpg --prompt "A portrait of a man wearing glasses" --num_images 4 --output outputs/man_glasses_gamma02_eta07_s6e15_st09.jpg --eta 0.7 --gamma 0.2 --start_timestep 6 --stop_timestep 15 --strength 0.9`
> 
> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044639-13fdb149-3ae9-49ee-ba56-468fe441ae1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDYzOS0xM2ZkYjE0OS0zYWU5LTQ5ZWUtYmE1Ni00NjhmZTQ0MWFlMWIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM2NDZiZTI5YTQ4MjFhNGVmYjFmNTI3YzY2ZTYzNjExMmUyNGY0NjM5OTMwOGQzY2FhM2E2NGI3ZmQ0MjEwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Fk7co5VIbuuKPUnDy2y79CdwujouZ1JFA8aFI2vMm1M"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044653-c2a6494f-6804-47d5-b35f-53fc25db1841.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDY1My1jMmE2NDk0Zi02ODA0LTQ3ZDUtYjM1Zi01M2ZjMjVkYjE4NDEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA3Y2Y5NThmNzA5OWI3MThlYWRhZWYxMjFmNDBhODlmMTM2ZmVkNGJkYjM4ZTVhODMxMzgyMDg0ODZhNTkxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oLetqtEuROYFjsJ5t2dZzXpfDXAiwULdcmClvGQ4FAc"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044659-cc777fd7-33c4-4509-9ac2-50c0092b0b27.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDY1OS1jYzc3N2ZkNy0zM2M0LTQ1MDktOWFjMi01MGMwMDkyYjBiMjcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE0MzEzNTVkODM5MDY4MTE3MjI1Mjk4YzgwMDNlZWJhMTRiOGEyMTU3NzNjZDE3YTI5NmQ5YzEwMTgyODFkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pTHkpqwhfTubI5R9ighGk5rm4D3tdIXWEq3WAxC6how"> <img alt="" width="20%" src="https://private-user-images.githubusercontent.com/4375159/379044677-f64a3e80-6802-4330-8330-2ce3f09e9b7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTA5MzIsIm5iZiI6MTcyOTY1MDYzMiwicGF0aCI6Ii80Mzc1MTU5LzM3OTA0NDY3Ny1mNjRhM2U4MC02ODAyLTQzMzAtODMzMC0yY2UzZjA5ZTliN2UuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDIzMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRmNWRiZDliOTFmNDk3YjlkYWM5YTFlNmUzZTY4NTk2ZDc4MTU0NjdjYTY4NGQxOTI4NTFkZjc2OGQ5N2UyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u9xt0qMtfaZLJtP21qtVssjLq2VU_2_N2xUeL7KmZfE">

Thank you for sharing! It seems different seeds have an impact on the results? By the way, do you have any experience with parameter tuning for other types of editing that you could share(e.g. styles)?

**Comment by raven38** [comment]
I implemented it for Flux.1 dev model. It improves the robustness against parametersl
